# Generated by Django 4.1.6 on 2023-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_num', models.CharField(max_length=10)),
                ('show_time', models.CharField(max_length=10)),
                ('seat_cat', models.CharField(max_length=2)),
                ('seat_num', models.CharField(max_length=2)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
